// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-33Nzi9I9EbQFjEdywkCF1rUA0Z3nxA0',
    appId: '1:288004034372:web:3953cc4206c6fc9c7e9111',
    messagingSenderId: '288004034372',
    projectId: 'crud-tarea-f95ed',
    authDomain: 'crud-tarea-f95ed.firebaseapp.com',
    storageBucket: 'crud-tarea-f95ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbkIwwb-0EQixodVMYcgXak5qbuB3RozM',
    appId: '1:288004034372:android:91da685c78e735b77e9111',
    messagingSenderId: '288004034372',
    projectId: 'crud-tarea-f95ed',
    storageBucket: 'crud-tarea-f95ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCm8PYo07aq2EHpGCDk80OQKpqQQDvO4',
    appId: '1:288004034372:ios:521815b1c5462e477e9111',
    messagingSenderId: '288004034372',
    projectId: 'crud-tarea-f95ed',
    storageBucket: 'crud-tarea-f95ed.appspot.com',
    iosBundleId: 'com.example.crudTarea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVCm8PYo07aq2EHpGCDk80OQKpqQQDvO4',
    appId: '1:288004034372:ios:521815b1c5462e477e9111',
    messagingSenderId: '288004034372',
    projectId: 'crud-tarea-f95ed',
    storageBucket: 'crud-tarea-f95ed.appspot.com',
    iosBundleId: 'com.example.crudTarea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-33Nzi9I9EbQFjEdywkCF1rUA0Z3nxA0',
    appId: '1:288004034372:web:4968d051e37acedd7e9111',
    messagingSenderId: '288004034372',
    projectId: 'crud-tarea-f95ed',
    authDomain: 'crud-tarea-f95ed.firebaseapp.com',
    storageBucket: 'crud-tarea-f95ed.appspot.com',
  );
}
